CREATE TABLE IF NOT EXISTS google_drive_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  access_token TEXT NULL,
  refresh_token TEXT NULL,
  scope TEXT NULL,
  token_type VARCHAR(100) NULL,
  expiry_date BIGINT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  drive_file_id VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'CREATED',
  message TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);