-- Add a counters row for clients so the consecutive code is generated by the
-- same atomic mechanism already used for orders and invoices. This guarantees
-- next code = MAX(existing) + 1 and never reuses deleted codes.
INSERT INTO counters (counter_key, prefix, current_value, padding)
SELECT 'clients', 'CLI', 0, 5 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM counters WHERE counter_key = 'clients');

-- Sync the freshly inserted counter to the highest existing client code so the
-- first generated code after this migration is MAX+1, never colliding with
-- legacy rows imported from previous installations.
UPDATE counters
SET current_value = COALESCE(
  (SELECT MAX(CAST(SUBSTRING_INDEX(code, '-', -1) AS UNSIGNED))
   FROM clients
   WHERE code REGEXP '^CLI-[0-9]+$'),
  current_value
)
WHERE counter_key = 'clients'
  AND COALESCE(
    (SELECT MAX(CAST(SUBSTRING_INDEX(code, '-', -1) AS UNSIGNED))
     FROM clients
     WHERE code REGEXP '^CLI-[0-9]+$'),
    0
  ) > current_value;
